import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Justin H',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="/dark-logo.svg"
					type="image/<generated>"
					sizes="<generated>"
				/>
				<link
					rel="apple-touch-icon"
					href="/dark-logo.svg"
					type="image/<generated>"
					sizes="<generated>"
				/>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			</head>
			<body className={`${geistSans.variable} antialiased scroll-smooth`}>
				{children}
			</body>
		</html>
	);
}
