import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import ScrollToTopButton from '@/components/ScrollToTopButton';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Justin H',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      url: '/light-logo.svg',
      sizes: '<generated>',
      media: '(prefers-color-scheme: dark)',
    },
    {
      rel: 'icon',
      url: '/dark-logo.svg',
      sizes: '<generated>',
      media: '(prefers-color-scheme: light)',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} antialiased scroll-smooth 
			mx-auto flex max-w-7xl flex-col min-h-screen`}
      >
        <Navbar />
        {children}
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
